name: flutter_ble
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  flutter_blue_plus: ^1.35.5
  logger: ^2.6.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  freezed: ^3.0.6
  json_serializable: ^6.9.5

flutter:

  uses-material-design: true
